// Embedded demo dataset, generated by scripts/embed-demo-data.js.
// Used by the standalone mode when the backend server is unreachable.
// Re run: node scripts/embed-demo-data.js
window.SETTLE_DEMO = {
 "orders": [
  {
   "order_id": "ORD1001",
   "customer": "Sneha Iyer",
   "expected_amount": 14999,
   "order_status": "paid",
   "order_date": "2026-09-02T09:00:00.000Z"
  },
  {
   "order_id": "ORD1002",
   "customer": "Priya Patel",
   "expected_amount": 6499,
   "order_status": "paid",
   "order_date": "2026-08-19T06:00:00.000Z"
  },
  {
   "order_id": "ORD1003",
   "customer": "Farah Khan",
   "expected_amount": 13999,
   "order_status": "pending",
   "order_date": "2026-08-15T11:00:00.000Z"
  },
  {
   "order_id": "ORD1004",
   "customer": "Karan Malhotra",
   "expected_amount": 18999,
   "order_status": "paid",
   "order_date": "2026-08-11T09:00:00.000Z"
  },
  {
   "order_id": "ORD1005",
   "customer": "Sneha Iyer",
   "expected_amount": 2999,
   "order_status": "paid",
   "order_date": "2026-08-21T03:00:00.000Z"
  },
  {
   "order_id": "ORD1006",
   "customer": "Shruti Kapoor",
   "expected_amount": 3999,
   "order_status": "paid",
   "order_date": "2026-08-09T03:00:00.000Z"
  },
  {
   "order_id": "ORD1007",
   "customer": "Ishita Bose",
   "expected_amount": 9499,
   "order_status": "paid",
   "order_date": "2026-09-01T06:00:00.000Z"
  },
  {
   "order_id": "ORD1008",
   "customer": "Divya Menon",
   "expected_amount": 2499,
   "order_status": "paid",
   "order_date": "2026-08-20T08:00:00.000Z"
  },
  {
   "order_id": "ORD1009",
   "customer": "Shruti Kapoor",
   "expected_amount": 6999,
   "order_status": "paid",
   "order_date": "2026-08-07T08:00:00.000Z"
  },
  {
   "order_id": "ORD1010",
   "customer": "Prakash Yadav",
   "expected_amount": 1499,
   "order_status": "paid",
   "order_date": "2026-08-30T01:00:00.000Z"
  },
  {
   "order_id": "ORD1011",
   "customer": "Harsha Vardhan",
   "expected_amount": 12499,
   "order_status": "paid",
   "order_date": "2026-08-16T07:00:00.000Z"
  },
  {
   "order_id": "ORD1012",
   "customer": "Farah Khan",
   "expected_amount": 649,
   "order_status": "paid",
   "order_date": "2026-08-24T02:00:00.000Z"
  },
  {
   "order_id": "ORD1013",
   "customer": "Kavya Nair",
   "expected_amount": 9999,
   "order_status": "paid",
   "order_date": "2026-08-19T07:00:00.000Z"
  },
  {
   "order_id": "ORD1014",
   "customer": "Karan Malhotra",
   "expected_amount": 6499,
   "order_status": "pending",
   "order_date": "2026-08-09T09:00:00.000Z"
  },
  {
   "order_id": "ORD1015",
   "customer": "Manish Tiwari",
   "expected_amount": 1499,
   "order_status": "paid",
   "order_date": "2026-08-21T01:00:00.000Z"
  },
  {
   "order_id": "ORD1016",
   "customer": "Anjali Desai",
   "expected_amount": 1999,
   "order_status": "paid",
   "order_date": "2026-08-05T09:00:00.000Z"
  },
  {
   "order_id": "ORD1017",
   "customer": "Amit Verma",
   "expected_amount": 6499,
   "order_status": "paid",
   "order_date": "2026-08-21T08:00:00.000Z"
  },
  {
   "order_id": "ORD1018",
   "customer": "Ishita Bose",
   "expected_amount": 2999,
   "order_status": "paid",
   "order_date": "2026-08-06T08:00:00.000Z"
  },
  {
   "order_id": "ORD1019",
   "customer": "Kavya Nair",
   "expected_amount": 5499,
   "order_status": "paid",
   "order_date": "2026-08-15T03:00:00.000Z"
  },
  {
   "order_id": "ORD1020",
   "customer": "Meera Krishnan",
   "expected_amount": 5499,
   "order_status": "paid",
   "order_date": "2026-08-08T02:00:00.000Z"
  },
  {
   "order_id": "ORD1021",
   "customer": "Amit Verma",
   "expected_amount": 1749,
   "order_status": "paid",
   "order_date": "2026-09-03T01:00:00.000Z"
  },
  {
   "order_id": "ORD1022",
   "customer": "Ravi Shankar",
   "expected_amount": 11249,
   "order_status": "paid",
   "order_date": "2026-08-20T02:00:00.000Z"
  },
  {
   "order_id": "ORD1023",
   "customer": "Farah Khan",
   "expected_amount": 5999,
   "order_status": "paid",
   "order_date": "2026-08-15T05:00:00.000Z"
  },
  {
   "order_id": "ORD1024",
   "customer": "Sanjay Das",
   "expected_amount": 17999,
   "order_status": "paid",
   "order_date": "2026-08-27T10:00:00.000Z"
  },
  {
   "order_id": "ORD1025",
   "customer": "Ramesh Iyer",
   "expected_amount": 799,
   "order_status": "paid",
   "order_date": "2026-09-01T10:00:00.000Z"
  },
  {
   "order_id": "ORD1026",
   "customer": "Arjun Reddy",
   "expected_amount": 8999,
   "order_status": "paid",
   "order_date": "2026-08-16T02:00:00.000Z"
  },
  {
   "order_id": "ORD1027",
   "customer": "Sanjay Das",
   "expected_amount": 18999,
   "order_status": "paid",
   "order_date": "2026-08-08T08:00:00.000Z"
  },
  {
   "order_id": "ORD1028",
   "customer": "Shruti Kapoor",
   "expected_amount": 1099,
   "order_status": "paid",
   "order_date": "2026-08-30T07:00:00.000Z"
  },
  {
   "order_id": "ORD1029",
   "customer": "Sneha Iyer",
   "expected_amount": 9499,
   "order_status": "paid",
   "order_date": "2026-08-17T09:00:00.000Z"
  },
  {
   "order_id": "ORD1030",
   "customer": "Farah Khan",
   "expected_amount": 2150,
   "order_status": "paid",
   "order_date": "2026-08-08T02:00:00.000Z"
  },
  {
   "order_id": "ORD1031",
   "customer": "Aishwarya Nair",
   "expected_amount": 499,
   "order_status": "paid",
   "order_date": "2026-08-05T03:00:00.000Z"
  },
  {
   "order_id": "ORD1032",
   "customer": "Ritu Saxena",
   "expected_amount": 3299,
   "order_status": "paid",
   "order_date": "2026-09-01T01:00:00.000Z"
  },
  {
   "order_id": "ORD1033",
   "customer": "Sneha Iyer",
   "expected_amount": 12499,
   "order_status": "paid",
   "order_date": "2026-09-01T10:00:00.000Z"
  },
  {
   "order_id": "ORD1034",
   "customer": "Deepak Choudhary",
   "expected_amount": 6499,
   "order_status": "paid",
   "order_date": "2026-09-03T11:00:00.000Z"
  },
  {
   "order_id": "ORD1035",
   "customer": "Vikram Singh",
   "expected_amount": 1999,
   "order_status": "paid",
   "order_date": "2026-08-15T06:00:00.000Z"
  },
  {
   "order_id": "ORD1036",
   "customer": "Lakshmi Rao",
   "expected_amount": 799,
   "order_status": "paid",
   "order_date": "2026-08-25T00:00:00.000Z"
  },
  {
   "order_id": "ORD1037",
   "customer": "Shruti Kapoor",
   "expected_amount": 5999,
   "order_status": "paid",
   "order_date": "2026-08-22T05:00:00.000Z"
  },
  {
   "order_id": "ORD1038",
   "customer": "Karan Malhotra",
   "expected_amount": 1749,
   "order_status": "paid",
   "order_date": "2026-08-14T10:00:00.000Z"
  },
  {
   "order_id": "ORD1039",
   "customer": "Rahul Sharma",
   "expected_amount": 2150,
   "order_status": "paid",
   "order_date": "2026-09-02T03:00:00.000Z"
  },
  {
   "order_id": "ORD1040",
   "customer": "Nikhil Joshi",
   "expected_amount": 1299,
   "order_status": "paid",
   "order_date": "2026-08-10T11:00:00.000Z"
  },
  {
   "order_id": "ORD1041",
   "customer": "Kunal Shah",
   "expected_amount": 4499,
   "order_status": "cancelled",
   "order_date": "2026-08-05T03:00:00.000Z"
  },
  {
   "order_id": "ORD1042",
   "customer": "Arjun Reddy",
   "expected_amount": 1999,
   "order_status": "paid",
   "order_date": "2026-09-03T02:00:00.000Z"
  },
  {
   "order_id": "ORD1043",
   "customer": "Arjun Reddy",
   "expected_amount": 2499,
   "order_status": "paid",
   "order_date": "2026-08-30T05:00:00.000Z"
  },
  {
   "order_id": "ORD1044",
   "customer": "Divya Menon",
   "expected_amount": 499,
   "order_status": "paid",
   "order_date": "2026-08-23T03:00:00.000Z"
  },
  {
   "order_id": "ORD1045",
   "customer": "Shruti Kapoor",
   "expected_amount": 11249,
   "order_status": "paid",
   "order_date": "2026-08-16T00:00:00.000Z"
  },
  {
   "order_id": "ORD1046",
   "customer": "Meera Krishnan",
   "expected_amount": 12499,
   "order_status": "pending",
   "order_date": "2026-08-13T04:00:00.000Z"
  },
  {
   "order_id": "ORD1047",
   "customer": "Lakshmi Rao",
   "expected_amount": 4999,
   "order_status": "paid",
   "order_date": "2026-08-07T04:00:00.000Z"
  },
  {
   "order_id": "ORD1048",
   "customer": "Pooja Kulkarni",
   "expected_amount": 9499,
   "order_status": "paid",
   "order_date": "2026-08-20T09:00:00.000Z"
  },
  {
   "order_id": "ORD1049",
   "customer": "Pallavi Iyer",
   "expected_amount": 6999,
   "order_status": "paid",
   "order_date": "2026-08-20T10:00:00.000Z"
  },
  {
   "order_id": "ORD1050",
   "customer": "Tanya Bhatia",
   "expected_amount": 5999,
   "order_status": "paid",
   "order_date": "2026-08-12T00:00:00.000Z"
  },
  {
   "order_id": "ORD1051",
   "customer": "Amit Verma",
   "expected_amount": 2999,
   "order_status": "paid",
   "order_date": "2026-08-30T02:00:00.000Z"
  },
  {
   "order_id": "ORD1052",
   "customer": "Neha Agarwal",
   "expected_amount": 2150,
   "order_status": "paid",
   "order_date": "2026-08-15T10:00:00.000Z"
  },
  {
   "order_id": "ORD1053",
   "customer": "Farah Khan",
   "expected_amount": 2999,
   "order_status": "paid",
   "order_date": "2026-08-16T11:00:00.000Z"
  },
  {
   "order_id": "ORD1054",
   "customer": "Suresh Babu",
   "expected_amount": 11249,
   "order_status": "paid",
   "order_date": "2026-08-06T10:00:00.000Z"
  },
  {
   "order_id": "ORD1055",
   "customer": "Pooja Kulkarni",
   "expected_amount": 1999,
   "order_status": "paid",
   "order_date": "2026-08-16T05:00:00.000Z"
  },
  {
   "order_id": "ORD1056",
   "customer": "Shruti Kapoor",
   "expected_amount": 12499,
   "order_status": "paid",
   "order_date": "2026-08-26T08:00:00.000Z"
  },
  {
   "order_id": "ORD1057",
   "customer": "Sneha Iyer",
   "expected_amount": 5999,
   "order_status": "paid",
   "order_date": "2026-08-06T08:00:00.000Z"
  },
  {
   "order_id": "ORD1058",
   "customer": "Ritu Saxena",
   "expected_amount": 6999,
   "order_status": "paid",
   "order_date": "2026-08-30T05:00:00.000Z"
  },
  {
   "order_id": "ORD1059",
   "customer": "Prakash Yadav",
   "expected_amount": 3999,
   "order_status": "paid",
   "order_date": "2026-08-07T03:00:00.000Z"
  },
  {
   "order_id": "ORD1060",
   "customer": "Sneha Iyer",
   "expected_amount": 7999,
   "order_status": "cancelled",
   "order_date": "2026-08-27T00:00:00.000Z"
  },
  {
   "order_id": "ORD1061",
   "customer": "Pooja Kulkarni",
   "expected_amount": 6999,
   "order_status": "paid",
   "order_date": "2026-08-23T11:00:00.000Z"
  },
  {
   "order_id": "ORD1062",
   "customer": "Shruti Kapoor",
   "expected_amount": 2150,
   "order_status": "paid",
   "order_date": "2026-08-16T02:00:00.000Z"
  },
  {
   "order_id": "ORD1063",
   "customer": "Farah Khan",
   "expected_amount": 17999,
   "order_status": "paid",
   "order_date": "2026-09-01T04:00:00.000Z"
  },
  {
   "order_id": "ORD1064",
   "customer": "Ananya Gupta",
   "expected_amount": 8999,
   "order_status": "paid",
   "order_date": "2026-08-11T11:00:00.000Z"
  },
  {
   "order_id": "ORD1065",
   "customer": "Arjun Reddy",
   "expected_amount": 24999,
   "order_status": "paid",
   "order_date": "2026-08-21T11:00:00.000Z"
  },
  {
   "order_id": "ORD1066",
   "customer": "Kunal Shah",
   "expected_amount": 2999,
   "order_status": "paid",
   "order_date": "2026-08-19T10:00:00.000Z"
  },
  {
   "order_id": "ORD1067",
   "customer": "Priya Patel",
   "expected_amount": 899,
   "order_status": "paid",
   "order_date": "2026-08-15T03:00:00.000Z"
  },
  {
   "order_id": "ORD1068",
   "customer": "Amit Verma",
   "expected_amount": 9999,
   "order_status": "paid",
   "order_date": "2026-08-06T08:00:00.000Z"
  },
  {
   "order_id": "ORD1069",
   "customer": "Ananya Gupta",
   "expected_amount": 999,
   "order_status": "paid",
   "order_date": "2026-08-13T04:00:00.000Z"
  },
  {
   "order_id": "ORD1070",
   "customer": "Ananya Gupta",
   "expected_amount": 1499,
   "order_status": "paid",
   "order_date": "2026-08-12T09:00:00.000Z"
  },
  {
   "order_id": "ORD1071",
   "customer": "Deepak Choudhary",
   "expected_amount": 1299,
   "order_status": "paid",
   "order_date": "2026-08-27T08:00:00.000Z"
  },
  {
   "order_id": "ORD1072",
   "customer": "Nidhi Verma",
   "expected_amount": 17999,
   "order_status": "paid",
   "order_date": "2026-09-01T02:00:00.000Z"
  },
  {
   "order_id": "ORD1073",
   "customer": "Neha Agarwal",
   "expected_amount": 3299,
   "order_status": "paid",
   "order_date": "2026-09-02T11:00:00.000Z"
  },
  {
   "order_id": "ORD1074",
   "customer": "Prakash Yadav",
   "expected_amount": 7999,
   "order_status": "paid",
   "order_date": "2026-08-29T10:00:00.000Z"
  },
  {
   "order_id": "ORD1075",
   "customer": "Pallavi Iyer",
   "expected_amount": 13999,
   "order_status": "paid",
   "order_date": "2026-08-13T07:00:00.000Z"
  },
  {
   "order_id": "ORD1076",
   "customer": "Vikram Singh",
   "expected_amount": 3299,
   "order_status": "paid",
   "order_date": "2026-08-16T10:00:00.000Z"
  },
  {
   "order_id": "ORD1077",
   "customer": "Aishwarya Nair",
   "expected_amount": 9499,
   "order_status": "paid",
   "order_date": "2026-08-15T11:00:00.000Z"
  },
  {
   "order_id": "ORD1078",
   "customer": "Harsha Vardhan",
   "expected_amount": 1299,
   "order_status": "paid",
   "order_date": "2026-08-18T01:00:00.000Z"
  },
  {
   "order_id": "ORD1079",
   "customer": "Farah Khan",
   "expected_amount": 1749,
   "order_status": "paid",
   "order_date": "2026-09-02T05:00:00.000Z"
  },
  {
   "order_id": "ORD1080",
   "customer": "Aishwarya Nair",
   "expected_amount": 14999,
   "order_status": "paid",
   "order_date": "2026-08-28T06:00:00.000Z"
  },
  {
   "order_id": "ORD1081",
   "customer": "Deepak Choudhary",
   "expected_amount": 499,
   "order_status": "paid",
   "order_date": "2026-08-20T00:00:00.000Z"
  },
  {
   "order_id": "ORD1082",
   "customer": "Arjun Reddy",
   "expected_amount": 5499,
   "order_status": "paid",
   "order_date": "2026-08-26T04:00:00.000Z"
  },
  {
   "order_id": "ORD1083",
   "customer": "Deepak Choudhary",
   "expected_amount": 5999,
   "order_status": "cancelled",
   "order_date": "2026-09-02T04:00:00.000Z"
  },
  {
   "order_id": "ORD1084",
   "customer": "Meera Krishnan",
   "expected_amount": 1299,
   "order_status": "paid",
   "order_date": "2026-08-18T00:00:00.000Z"
  },
  {
   "order_id": "ORD1085",
   "customer": "Karan Malhotra",
   "expected_amount": 899,
   "order_status": "paid",
   "order_date": "2026-09-03T06:00:00.000Z"
  },
  {
   "order_id": "ORD1086",
   "customer": "Priya Patel",
   "expected_amount": 3499,
   "order_status": "paid",
   "order_date": "2026-08-15T00:00:00.000Z"
  },
  {
   "order_id": "ORD1087",
   "customer": "Karan Malhotra",
   "expected_amount": 4499,
   "order_status": "paid",
   "order_date": "2026-08-10T00:00:00.000Z"
  },
  {
   "order_id": "ORD1088",
   "customer": "Ritu Saxena",
   "expected_amount": 499,
   "order_status": "paid",
   "order_date": "2026-08-17T06:00:00.000Z"
  },
  {
   "order_id": "ORD1089",
   "customer": "Pallavi Iyer",
   "expected_amount": 24999,
   "order_status": "paid",
   "order_date": "2026-08-20T11:00:00.000Z"
  },
  {
   "order_id": "ORD1090",
   "customer": "Arjun Reddy",
   "expected_amount": 7999,
   "order_status": "paid",
   "order_date": "2026-08-23T07:00:00.000Z"
  },
  {
   "order_id": "ORD1091",
   "customer": "Sanjay Das",
   "expected_amount": 1499,
   "order_status": "paid",
   "order_date": "2026-08-23T07:00:00.000Z"
  },
  {
   "order_id": "ORD1092",
   "customer": "Mohit Agarwal",
   "expected_amount": 1299,
   "order_status": "paid",
   "order_date": "2026-08-29T07:00:00.000Z"
  },
  {
   "order_id": "ORD1093",
   "customer": "Vikram Singh",
   "expected_amount": 5499,
   "order_status": "paid",
   "order_date": "2026-08-05T03:00:00.000Z"
  },
  {
   "order_id": "ORD1094",
   "customer": "Divya Menon",
   "expected_amount": 1749,
   "order_status": "paid",
   "order_date": "2026-08-06T01:00:00.000Z"
  },
  {
   "order_id": "ORD1095",
   "customer": "Ananya Gupta",
   "expected_amount": 13999,
   "order_status": "paid",
   "order_date": "2026-08-09T00:00:00.000Z"
  },
  {
   "order_id": "ORD1096",
   "customer": "Arjun Reddy",
   "expected_amount": 5499,
   "order_status": "paid",
   "order_date": "2026-08-16T06:00:00.000Z"
  },
  {
   "order_id": "ORD1097",
   "customer": "Ramesh Iyer",
   "expected_amount": 649,
   "order_status": "paid",
   "order_date": "2026-08-30T11:00:00.000Z"
  },
  {
   "order_id": "ORD1098",
   "customer": "Ravi Shankar",
   "expected_amount": 1099,
   "order_status": "paid",
   "order_date": "2026-08-13T00:00:00.000Z"
  },
  {
   "order_id": "ORD1099",
   "customer": "Farah Khan",
   "expected_amount": 18999,
   "order_status": "paid",
   "order_date": "2026-08-07T06:00:00.000Z"
  },
  {
   "order_id": "ORD1100",
   "customer": "Suresh Babu",
   "expected_amount": 3499,
   "order_status": "paid",
   "order_date": "2026-09-01T11:00:00.000Z"
  },
  {
   "order_id": "ORD1101",
   "customer": "Sneha Iyer",
   "expected_amount": 5999,
   "order_status": "paid",
   "order_date": "2026-08-12T07:00:00.000Z"
  },
  {
   "order_id": "ORD1102",
   "customer": "Swati Mishra",
   "expected_amount": 2499,
   "order_status": "paid",
   "order_date": "2026-08-21T06:00:00.000Z"
  },
  {
   "order_id": "ORD1103",
   "customer": "Pooja Kulkarni",
   "expected_amount": 24999,
   "order_status": "paid",
   "order_date": "2026-08-25T06:00:00.000Z"
  },
  {
   "order_id": "ORD1104",
   "customer": "Lakshmi Rao",
   "expected_amount": 4499,
   "order_status": "paid",
   "order_date": "2026-08-07T03:00:00.000Z"
  },
  {
   "order_id": "ORD1105",
   "customer": "Priya Patel",
   "expected_amount": 8999,
   "order_status": "paid",
   "order_date": "2026-08-23T10:00:00.000Z"
  },
  {
   "order_id": "ORD1106",
   "customer": "Siddharth Pillai",
   "expected_amount": 6499,
   "order_status": "paid",
   "order_date": "2026-08-31T09:00:00.000Z"
  },
  {
   "order_id": "ORD1107",
   "customer": "Tanya Bhatia",
   "expected_amount": 649,
   "order_status": "paid",
   "order_date": "2026-09-02T02:00:00.000Z"
  },
  {
   "order_id": "ORD1108",
   "customer": "Ananya Gupta",
   "expected_amount": 7999,
   "order_status": "paid",
   "order_date": "2026-08-26T08:00:00.000Z"
  },
  {
   "order_id": "ORD1109",
   "customer": "Rohan Mehta",
   "expected_amount": 5499,
   "order_status": "paid",
   "order_date": "2026-08-27T05:00:00.000Z"
  },
  {
   "order_id": "ORD1110",
   "customer": "Ritu Saxena",
   "expected_amount": 24999,
   "order_status": "paid",
   "order_date": "2026-08-21T02:00:00.000Z"
  },
  {
   "order_id": "ORD1111",
   "customer": "Gaurav Khanna",
   "expected_amount": 4999,
   "order_status": "paid",
   "order_date": "2026-08-29T02:00:00.000Z"
  },
  {
   "order_id": "ORD1112",
   "customer": "Prakash Yadav",
   "expected_amount": 14999,
   "order_status": "paid",
   "order_date": "2026-08-20T00:00:00.000Z"
  },
  {
   "order_id": "ORD1113",
   "customer": "Aditya Kulkarni",
   "expected_amount": 649,
   "order_status": "paid",
   "order_date": "2026-08-23T06:00:00.000Z"
  },
  {
   "order_id": "ORD1114",
   "customer": "Shruti Kapoor",
   "expected_amount": 3999,
   "order_status": "paid",
   "order_date": "2026-08-05T04:00:00.000Z"
  },
  {
   "order_id": "ORD1115",
   "customer": "Gaurav Khanna",
   "expected_amount": 12499,
   "order_status": "paid",
   "order_date": "2026-08-25T04:00:00.000Z"
  },
  {
   "order_id": "ORD1116",
   "customer": "Kavya Nair",
   "expected_amount": 3499,
   "order_status": "paid",
   "order_date": "2026-08-31T01:00:00.000Z"
  },
  {
   "order_id": "ORD1117",
   "customer": "Shruti Kapoor",
   "expected_amount": 7999,
   "order_status": "paid",
   "order_date": "2026-08-14T08:00:00.000Z"
  },
  {
   "order_id": "ORD1118",
   "customer": "Ritu Saxena",
   "expected_amount": 499,
   "order_status": "paid",
   "order_date": "2026-08-21T11:00:00.000Z"
  },
  {
   "order_id": "ORD1119",
   "customer": "Ramesh Iyer",
   "expected_amount": 12499,
   "order_status": "paid",
   "order_date": "2026-09-01T07:00:00.000Z"
  },
  {
   "order_id": "ORD1120",
   "customer": "Priya Patel",
   "expected_amount": 6499,
   "order_status": "paid",
   "order_date": "2026-08-15T06:00:00.000Z"
  },
  {
   "order_id": "ORD1121",
   "customer": "Sanjay Das",
   "expected_amount": 3999,
   "order_status": "paid",
   "order_date": "2026-09-03T00:00:00.000Z"
  },
  {
   "order_id": "ORD1122",
   "customer": "Geeta Devi",
   "expected_amount": 1999,
   "order_status": "paid",
   "order_date": "2026-08-23T01:00:00.000Z"
  },
  {
   "order_id": "ORD1123",
   "customer": "Ritu Saxena",
   "expected_amount": 499,
   "order_status": "paid",
   "order_date": "2026-08-13T05:00:00.000Z"
  },
  {
   "order_id": "ORD1124",
   "customer": "Ananya Gupta",
   "expected_amount": 1749,
   "order_status": "paid",
   "order_date": "2026-08-15T01:00:00.000Z"
  },
  {
   "order_id": "ORD1125",
   "customer": "Anjali Desai",
   "expected_amount": 1499,
   "order_status": "paid",
   "order_date": "2026-08-23T11:00:00.000Z"
  },
  {
   "order_id": "ORD1126",
   "customer": "Pooja Kulkarni",
   "expected_amount": 6999,
   "order_status": "paid",
   "order_date": "2026-09-03T00:00:00.000Z"
  },
  {
   "order_id": "ORD1127",
   "customer": "Karan Malhotra",
   "expected_amount": 8999,
   "order_status": "paid",
   "order_date": "2026-08-14T01:00:00.000Z"
  }
 ],
 "payments": [
  {
   "payment_id": "pay_82e34685",
   "order_id": "ORD1020",
   "amount": 5499,
   "status": "captured",
   "customer": "Meera Krishnan",
   "timestamp": "2026-08-07T04:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_241f4abc",
   "order_id": "ORD1089",
   "amount": 24999,
   "status": "captured",
   "customer": "Pallavi Iyer",
   "timestamp": "2026-08-14T09:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_66b653e0",
   "order_id": "ORD1063",
   "amount": 17999,
   "status": "captured",
   "customer": "Farah Khan",
   "timestamp": "2026-08-27T02:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_24155671",
   "order_id": "ORD1054",
   "amount": 11249,
   "status": "captured",
   "customer": "Suresh Babu",
   "timestamp": "2026-08-10T04:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_76ce9ffb",
   "order_id": "ORD1072",
   "amount": 17999,
   "status": "captured",
   "customer": "Nidhi Verma",
   "timestamp": "2026-08-07T02:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_cbbdfd79",
   "order_id": "ORD1093",
   "amount": 5499,
   "status": "captured",
   "customer": "Vikram Singh",
   "timestamp": "2026-08-26T04:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_b0dda214",
   "order_id": "ORD1043",
   "amount": 2499,
   "status": "captured",
   "customer": "Arjun Reddy",
   "timestamp": "2026-08-05T08:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_7e621430",
   "order_id": "ORD1120",
   "amount": 6499,
   "status": "captured",
   "customer": "Priya Patel",
   "timestamp": "2026-08-29T05:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_647a26a5",
   "order_id": "ORD1114",
   "amount": 3999,
   "status": "captured",
   "customer": "Shruti Kapoor",
   "timestamp": "2026-08-07T09:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_a07d790c",
   "order_id": "ORD1086",
   "amount": 3499,
   "status": "captured",
   "customer": "Priya Patel",
   "timestamp": "2026-09-01T05:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_e1234dce",
   "order_id": "ORD1018",
   "amount": 2999,
   "status": "captured",
   "customer": "Ishita Bose",
   "timestamp": "2026-08-28T03:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_ce603b6a",
   "order_id": "ORD1002",
   "amount": 6499,
   "status": "captured",
   "customer": "Priya Patel",
   "timestamp": "2026-08-05T10:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_11a1590b",
   "order_id": "ORD1085",
   "amount": 899,
   "status": "captured",
   "customer": "Karan Malhotra",
   "timestamp": "2026-08-15T06:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_9fbc2295",
   "order_id": "ORD1007",
   "amount": 9499,
   "status": "captured",
   "customer": "Ishita Bose",
   "timestamp": "2026-08-31T04:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_a1508c82",
   "order_id": "ORD1044",
   "amount": 499,
   "status": "captured",
   "customer": "Divya Menon",
   "timestamp": "2026-08-23T00:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_5f2543c2",
   "order_id": "ORD1121",
   "amount": 3999,
   "status": "captured",
   "customer": "Sanjay Das",
   "timestamp": "2026-08-20T05:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_cee28a00",
   "order_id": "ORD1011",
   "amount": 12499,
   "status": "captured",
   "customer": "Harsha Vardhan",
   "timestamp": "2026-08-26T07:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_087991a1",
   "order_id": "ORD1061",
   "amount": 6999,
   "status": "captured",
   "customer": "Pooja Kulkarni",
   "timestamp": "2026-08-31T01:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_97722d90",
   "order_id": "ORD1069",
   "amount": 999,
   "status": "captured",
   "customer": "Ananya Gupta",
   "timestamp": "2026-09-01T09:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_8e2a9910",
   "order_id": "ORD1103",
   "amount": 24999,
   "status": "captured",
   "customer": "Pooja Kulkarni",
   "timestamp": "2026-08-26T03:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_f4f73b7a",
   "order_id": "ORD1075",
   "amount": 13999,
   "status": "captured",
   "customer": "Pallavi Iyer",
   "timestamp": "2026-08-09T06:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_2b665bd3",
   "order_id": "ORD1051",
   "amount": 2999,
   "status": "captured",
   "customer": "Amit Verma",
   "timestamp": "2026-08-26T09:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_e43617b7",
   "order_id": "ORD1068",
   "amount": 9999,
   "status": "captured",
   "customer": "Amit Verma",
   "timestamp": "2026-08-19T10:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_0c35ed0d",
   "order_id": "ORD1111",
   "amount": 4999,
   "status": "captured",
   "customer": "Gaurav Khanna",
   "timestamp": "2026-08-16T04:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_13729717",
   "order_id": "ORD1027",
   "amount": 18999,
   "status": "captured",
   "customer": "Sanjay Das",
   "timestamp": "2026-08-26T03:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_ab99443b",
   "order_id": "ORD1006",
   "amount": 3999,
   "status": "captured",
   "customer": "Shruti Kapoor",
   "timestamp": "2026-08-18T08:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_314ecafc",
   "order_id": "ORD1094",
   "amount": 1749,
   "status": "captured",
   "customer": "Divya Menon",
   "timestamp": "2026-08-29T05:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_65209457",
   "order_id": "ORD1040",
   "amount": 1299,
   "status": "captured",
   "customer": "Nikhil Joshi",
   "timestamp": "2026-08-23T06:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_b4dfba08",
   "order_id": "ORD1052",
   "amount": 2150,
   "status": "captured",
   "customer": "Neha Agarwal",
   "timestamp": "2026-08-06T06:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_9832087b",
   "order_id": "ORD1015",
   "amount": 1499,
   "status": "captured",
   "customer": "Manish Tiwari",
   "timestamp": "2026-08-16T00:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_72b280e8",
   "order_id": "ORD1058",
   "amount": 6999,
   "status": "captured",
   "customer": "Ritu Saxena",
   "timestamp": "2026-09-02T08:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_d0f896c3",
   "order_id": "ORD1074",
   "amount": 7999,
   "status": "captured",
   "customer": "Prakash Yadav",
   "timestamp": "2026-08-14T05:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_4e75336f",
   "order_id": "ORD1122",
   "amount": 1999,
   "status": "captured",
   "customer": "Geeta Devi",
   "timestamp": "2026-08-19T08:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_ac08cc5b",
   "order_id": "ORD1037",
   "amount": 5999,
   "status": "captured",
   "customer": "Shruti Kapoor",
   "timestamp": "2026-08-24T04:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_f1e50dd8",
   "order_id": "ORD1073",
   "amount": 3299,
   "status": "captured",
   "customer": "Neha Agarwal",
   "timestamp": "2026-08-17T11:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_5351bc64",
   "order_id": "ORD1100",
   "amount": 3499,
   "status": "captured",
   "customer": "Suresh Babu",
   "timestamp": "2026-08-05T08:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_6b73a6ce",
   "order_id": "ORD1039",
   "amount": 2150,
   "status": "captured",
   "customer": "Rahul Sharma",
   "timestamp": "2026-08-05T09:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_f49f5a74",
   "order_id": "ORD1101",
   "amount": 5999,
   "status": "captured",
   "customer": "Sneha Iyer",
   "timestamp": "2026-08-11T08:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_91ea05ad",
   "order_id": "ORD1095",
   "amount": 13999,
   "status": "captured",
   "customer": "Ananya Gupta",
   "timestamp": "2026-08-05T06:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_2f2efa9b",
   "order_id": "ORD1117",
   "amount": 7999,
   "status": "captured",
   "customer": "Shruti Kapoor",
   "timestamp": "2026-08-29T00:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_5ceb133e",
   "order_id": "ORD1080",
   "amount": 14999,
   "status": "captured",
   "customer": "Aishwarya Nair",
   "timestamp": "2026-08-08T06:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_44e2c746",
   "order_id": "ORD1097",
   "amount": 649,
   "status": "captured",
   "customer": "Ramesh Iyer",
   "timestamp": "2026-08-30T07:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_696e3219",
   "order_id": "ORD1012",
   "amount": 649,
   "status": "captured",
   "customer": "Farah Khan",
   "timestamp": "2026-08-26T04:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_36bcc172",
   "order_id": "ORD1025",
   "amount": 799,
   "status": "captured",
   "customer": "Ramesh Iyer",
   "timestamp": "2026-08-11T01:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_253d9983",
   "order_id": "ORD1038",
   "amount": 1749,
   "status": "captured",
   "customer": "Karan Malhotra",
   "timestamp": "2026-08-17T11:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_5129295f",
   "order_id": "ORD1092",
   "amount": 1299,
   "status": "captured",
   "customer": "Mohit Agarwal",
   "timestamp": "2026-08-24T11:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_5017773f",
   "order_id": "ORD1104",
   "amount": 4499,
   "status": "captured",
   "customer": "Lakshmi Rao",
   "timestamp": "2026-08-10T10:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_a89b8d24",
   "order_id": "ORD1077",
   "amount": 9499,
   "status": "captured",
   "customer": "Aishwarya Nair",
   "timestamp": "2026-08-15T04:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_6d2c376e",
   "order_id": "ORD1107",
   "amount": 649,
   "status": "captured",
   "customer": "Tanya Bhatia",
   "timestamp": "2026-09-02T05:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_82d80513",
   "order_id": "ORD1109",
   "amount": 5499,
   "status": "captured",
   "customer": "Rohan Mehta",
   "timestamp": "2026-08-08T07:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_cf05c7f0",
   "order_id": "ORD1022",
   "amount": 11249,
   "status": "captured",
   "customer": "Ravi Shankar",
   "timestamp": "2026-08-24T07:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_c15377c1",
   "order_id": "ORD1026",
   "amount": 8999,
   "status": "captured",
   "customer": "Arjun Reddy",
   "timestamp": "2026-08-25T08:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_e8f67aae",
   "order_id": "ORD1076",
   "amount": 3299,
   "status": "captured",
   "customer": "Vikram Singh",
   "timestamp": "2026-08-26T06:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_2c6e8c9d",
   "order_id": "ORD1070",
   "amount": 1499,
   "status": "captured",
   "customer": "Ananya Gupta",
   "timestamp": "2026-08-24T07:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_e662cd15",
   "order_id": "ORD1096",
   "amount": 5499,
   "status": "captured",
   "customer": "Arjun Reddy",
   "timestamp": "2026-08-27T08:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_5fdef82e",
   "order_id": "ORD1028",
   "amount": 1099,
   "status": "captured",
   "customer": "Shruti Kapoor",
   "timestamp": "2026-08-20T01:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_8ea6568e",
   "order_id": "ORD1119",
   "amount": 12499,
   "status": "captured",
   "customer": "Ramesh Iyer",
   "timestamp": "2026-08-15T04:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_1836d51d",
   "order_id": "ORD1124",
   "amount": 1749,
   "status": "captured",
   "customer": "Ananya Gupta",
   "timestamp": "2026-08-22T00:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_4692ca2d",
   "order_id": "ORD1127",
   "amount": 8999,
   "status": "captured",
   "customer": "Karan Malhotra",
   "timestamp": "2026-08-28T10:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_b0f1b0cb",
   "order_id": "ORD1009",
   "amount": 6999,
   "status": "captured",
   "customer": "Shruti Kapoor",
   "timestamp": "2026-08-06T09:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_1d622995",
   "order_id": "ORD1017",
   "amount": 6499,
   "status": "captured",
   "customer": "Amit Verma",
   "timestamp": "2026-08-23T11:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_9bfaf68b",
   "order_id": "ORD1071",
   "amount": 1299,
   "status": "captured",
   "customer": "Deepak Choudhary",
   "timestamp": "2026-08-11T06:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_dfe7d800",
   "order_id": "ORD1116",
   "amount": 3499,
   "status": "captured",
   "customer": "Kavya Nair",
   "timestamp": "2026-08-26T10:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_7a7e7032",
   "order_id": "ORD1005",
   "amount": 2999,
   "status": "captured",
   "customer": "Sneha Iyer",
   "timestamp": "2026-08-13T01:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_f19a13c9",
   "order_id": "ORD1123",
   "amount": 499,
   "status": "captured",
   "customer": "Ritu Saxena",
   "timestamp": "2026-08-26T01:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_ac4673e7",
   "order_id": "ORD1113",
   "amount": 649,
   "status": "captured",
   "customer": "Aditya Kulkarni",
   "timestamp": "2026-08-22T01:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_bd0f6afe",
   "order_id": "ORD1115",
   "amount": 12499,
   "status": "captured",
   "customer": "Gaurav Khanna",
   "timestamp": "2026-08-22T05:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_499d8103",
   "order_id": "ORD1035",
   "amount": 1999,
   "status": "captured",
   "customer": "Vikram Singh",
   "timestamp": "2026-08-22T05:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_92abc5a0",
   "order_id": "ORD1110",
   "amount": 24999,
   "status": "captured",
   "customer": "Ritu Saxena",
   "timestamp": "2026-08-20T06:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_438bab48",
   "order_id": "ORD1048",
   "amount": 9499,
   "status": "captured",
   "customer": "Pooja Kulkarni",
   "timestamp": "2026-08-19T00:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_fdf5b284",
   "order_id": "ORD1106",
   "amount": 6499,
   "status": "captured",
   "customer": "Siddharth Pillai",
   "timestamp": "2026-08-18T08:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_737a6d11",
   "order_id": "ORD1091",
   "amount": 1499,
   "status": "captured",
   "customer": "Sanjay Das",
   "timestamp": "2026-08-22T07:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_45624546",
   "order_id": "ORD1045",
   "amount": 11249,
   "status": "captured",
   "customer": "Shruti Kapoor",
   "timestamp": "2026-08-06T11:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_bc16bee8",
   "order_id": "ORD1087",
   "amount": 4499,
   "status": "captured",
   "customer": "Karan Malhotra",
   "timestamp": "2026-08-26T06:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_b80c07e1",
   "order_id": "ORD1019",
   "amount": 5499,
   "status": "captured",
   "customer": "Kavya Nair",
   "timestamp": "2026-08-08T10:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_59fc802d",
   "order_id": "ORD1023",
   "amount": 5999,
   "status": "captured",
   "customer": "Farah Khan",
   "timestamp": "2026-08-24T00:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_f921ce3a",
   "order_id": "ORD1066",
   "amount": 2999,
   "status": "captured",
   "customer": "Kunal Shah",
   "timestamp": "2026-08-10T01:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_c059ce02",
   "order_id": "ORD1118",
   "amount": 499,
   "status": "captured",
   "customer": "Ritu Saxena",
   "timestamp": "2026-08-25T04:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_e2ec634b",
   "order_id": "ORD1021",
   "amount": 1749,
   "status": "captured",
   "customer": "Amit Verma",
   "timestamp": "2026-08-20T11:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_f6aa1a01",
   "order_id": "ORD1059",
   "amount": 3999,
   "status": "captured",
   "customer": "Prakash Yadav",
   "timestamp": "2026-08-19T05:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_0766dc2b",
   "order_id": "ORD1032",
   "amount": 3299,
   "status": "captured",
   "customer": "Ritu Saxena",
   "timestamp": "2026-08-08T10:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_ea28653d",
   "order_id": "ORD1079",
   "amount": 1749,
   "status": "captured",
   "customer": "Farah Khan",
   "timestamp": "2026-08-25T03:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_b537866c",
   "order_id": "ORD1090",
   "amount": 7999,
   "status": "captured",
   "customer": "Arjun Reddy",
   "timestamp": "2026-08-13T10:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_d5aecaa3",
   "order_id": "ORD1065",
   "amount": 24999,
   "status": "captured",
   "customer": "Arjun Reddy",
   "timestamp": "2026-08-21T08:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_46044787",
   "order_id": "ORD1112",
   "amount": 14999,
   "status": "captured",
   "customer": "Prakash Yadav",
   "timestamp": "2026-08-05T08:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_55d84913",
   "order_id": "ORD1010",
   "amount": 1499,
   "status": "captured",
   "customer": "Prakash Yadav",
   "timestamp": "2026-08-05T01:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_2f3bc48d",
   "order_id": "ORD1029",
   "amount": 9499,
   "status": "captured",
   "customer": "Sneha Iyer",
   "timestamp": "2026-08-30T01:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_bb459c4b",
   "order_id": "ORD1004",
   "amount": 18999,
   "status": "captured",
   "customer": "Karan Malhotra",
   "timestamp": "2026-08-27T07:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_cc8f5950",
   "order_id": "ORD1102",
   "amount": 2499,
   "status": "captured",
   "customer": "Swati Mishra",
   "timestamp": "2026-08-20T05:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_1e722dec",
   "order_id": "ORD1098",
   "amount": 1099,
   "status": "captured",
   "customer": "Ravi Shankar",
   "timestamp": "2026-08-31T03:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_194be229",
   "order_id": "ORD1034",
   "amount": 6499,
   "status": "captured",
   "customer": "Deepak Choudhary",
   "timestamp": "2026-08-05T08:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_9ba58b9e",
   "order_id": "ORD1013",
   "amount": 9999,
   "status": "captured",
   "customer": "Kavya Nair",
   "timestamp": "2026-08-28T02:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_df98b3ef",
   "order_id": "ORD1064",
   "amount": 8999,
   "status": "captured",
   "customer": "Ananya Gupta",
   "timestamp": "2026-08-15T08:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_1f7b3318",
   "order_id": "ORD1078",
   "amount": 1299,
   "status": "captured",
   "customer": "Harsha Vardhan",
   "timestamp": "2026-08-08T01:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_e4e8138a",
   "order_id": "ORD1050",
   "amount": 5999,
   "status": "captured",
   "customer": "Tanya Bhatia",
   "timestamp": "2026-08-06T02:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_bf2a66a3",
   "order_id": "ORD1056",
   "amount": 12499,
   "status": "captured",
   "customer": "Shruti Kapoor",
   "timestamp": "2026-08-05T05:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_61ddd331",
   "order_id": "ORD1016",
   "amount": 1999,
   "status": "captured",
   "customer": "Anjali Desai",
   "timestamp": "2026-08-19T07:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_342eb10e",
   "order_id": "ORD1033",
   "amount": 12499,
   "status": "captured",
   "customer": "Sneha Iyer",
   "timestamp": "2026-08-30T00:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_8881b26f",
   "order_id": "ORD1088",
   "amount": 499,
   "status": "captured",
   "customer": "Ritu Saxena",
   "timestamp": "2026-08-08T10:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_6448fb43",
   "order_id": "ORD1036",
   "amount": 799,
   "status": "captured",
   "customer": "Lakshmi Rao",
   "timestamp": "2026-08-26T08:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_ce49d6b2",
   "order_id": "ORD1003",
   "amount": 13999,
   "status": "pending",
   "customer": "Farah Khan",
   "timestamp": "2026-08-22T10:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_87b0ea8d",
   "order_id": "ORD1014",
   "amount": 6499,
   "status": "pending",
   "customer": "Karan Malhotra",
   "timestamp": "2026-09-01T01:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_387d9e73",
   "order_id": "ORD1046",
   "amount": 12499,
   "status": "pending",
   "customer": "Meera Krishnan",
   "timestamp": "2026-08-27T05:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_adba319b",
   "order_id": "ORD1126",
   "amount": 6444,
   "status": "captured",
   "customer": "Pooja Kulkarni",
   "timestamp": "2026-08-09T04:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_fab73ab7",
   "order_id": "ORD1042",
   "amount": 1444,
   "status": "captured",
   "customer": "Arjun Reddy",
   "timestamp": "2026-08-22T11:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_54ea7f91",
   "order_id": "ORD1031",
   "amount": 166,
   "status": "captured",
   "customer": "Aishwarya Nair",
   "timestamp": "2026-08-30T04:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_229a1b37",
   "order_id": "ORD1081",
   "amount": 55,
   "status": "captured",
   "customer": "Deepak Choudhary",
   "timestamp": "2026-08-07T04:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_92ec24b6",
   "order_id": "ORD1024",
   "amount": 17777,
   "status": "captured",
   "customer": "Sanjay Das",
   "timestamp": "2026-08-11T04:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_4ff52bbe",
   "order_id": "ORD1030",
   "amount": 5499,
   "status": "captured",
   "customer": "Farah Khan",
   "timestamp": "2026-08-10T09:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_f060dc58",
   "order_id": "ORD1030",
   "amount": 5499,
   "status": "captured",
   "customer": "Farah Khan",
   "timestamp": "2026-08-07T08:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_14b9529c",
   "order_id": "ORD1049",
   "amount": 9999,
   "status": "captured",
   "customer": "Pallavi Iyer",
   "timestamp": "2026-08-20T08:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_ed9b6691",
   "order_id": "ORD1049",
   "amount": 9999,
   "status": "captured",
   "customer": "Pallavi Iyer",
   "timestamp": "2026-08-05T08:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_a2a48c62",
   "order_id": "ORD1001",
   "amount": 899,
   "status": "captured",
   "customer": "Sneha Iyer",
   "timestamp": "2026-09-02T01:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_06b55a06",
   "order_id": "ORD1001",
   "amount": 899,
   "status": "captured",
   "customer": "Sneha Iyer",
   "timestamp": "2026-08-19T00:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_ae43a2f5",
   "order_id": "ORD1060",
   "amount": 7999,
   "status": "captured",
   "customer": "Sneha Iyer",
   "timestamp": "2026-08-19T06:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_a5367c16",
   "order_id": "ORD1083",
   "amount": 5999,
   "status": "captured",
   "customer": "Deepak Choudhary",
   "timestamp": "2026-09-02T01:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_fcb4e242",
   "order_id": "ORD1041",
   "amount": 4499,
   "status": "captured",
   "customer": "Kunal Shah",
   "timestamp": "2026-08-29T02:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_17b8d13f",
   "order_id": "ORD1055",
   "amount": 1999,
   "status": "refunded",
   "customer": "Pooja Kulkarni",
   "timestamp": "2026-08-06T05:00:00.000Z",
   "refund_amount": 499
  },
  {
   "payment_id": "pay_5759f784",
   "order_id": "ORD1008",
   "amount": 2499,
   "status": "refunded",
   "customer": "Divya Menon",
   "timestamp": "2026-08-19T06:00:00.000Z",
   "refund_amount": 799
  },
  {
   "payment_id": "pay_c99d8be5",
   "order_id": "ORD1082",
   "amount": 18999,
   "status": "captured",
   "customer": "Arjun Reddy",
   "timestamp": "2026-08-24T08:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_664642ff",
   "order_id": "ORD1125",
   "amount": 1499,
   "status": "failed",
   "customer": "Anjali Desai",
   "timestamp": "2026-08-14T03:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_4e790ce7",
   "order_id": "",
   "amount": 4999,
   "status": "captured",
   "customer": "Geeta Devi",
   "timestamp": "2026-08-09T08:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_74d53157",
   "order_id": "",
   "amount": 2499,
   "status": "captured",
   "customer": "Aditya Kulkarni",
   "timestamp": "2026-08-29T09:00:00.000Z",
   "refund_amount": 0
  },
  {
   "payment_id": "pay_180dd826",
   "order_id": "",
   "amount": 1299,
   "status": "captured",
   "customer": "Vikram Singh",
   "timestamp": "2026-09-03T03:00:00.000Z",
   "refund_amount": 0
  }
 ]
};
